2020-11-19 03:18:58 [http-nio-8444-exec-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 04:51:29 [http-nio-8444-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/careGiver] threw exception [Request processing failed; nested exception is com.qdm.cg.clients.exceptionhandler.NoIssueFoundException: No ID found] with root cause
com.qdm.cg.clients.exceptionhandler.NoIssueFoundException: No ID found
	at com.qdm.cg.clients.serviceimpl.ManageClientService.lambda$getActivitySummary$3(ManageClientService.java:281)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.qdm.cg.clients.serviceimpl.ManageClientService.getActivitySummary(ManageClientService.java:281)
	at com.qdm.cg.clients.controller.ManageClientsController.getActivitySummary(ManageClientsController.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-19 05:13:12 [http-nio-8444-exec-10] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:30:03 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:30:38 [http-nio-8444-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:31:01 [http-nio-8444-exec-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:31:17 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:31:44 [http-nio-8444-exec-10] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:32:23 [http-nio-8444-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:35:51 [http-nio-8444-exec-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:35:59 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:37:17 [http-nio-8444-exec-10] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:41:38 [http-nio-8444-exec-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:42:06 [http-nio-8444-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:42:19 [http-nio-8444-exec-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:43:21 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:43:40 [http-nio-8444-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:44:14 [http-nio-8444-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:54:20 [http-nio-8444-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:55:03 [http-nio-8444-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:55:45 [http-nio-8444-exec-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:56:08 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:56:27 [http-nio-8444-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:58:20 [http-nio-8444-exec-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 05:58:47 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:00:24 [http-nio-8444-exec-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:00:30 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:01:34 [http-nio-8444-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:15:03 [http-nio-8444-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:15:19 [http-nio-8444-exec-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:15:43 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:21:59 [http-nio-8444-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:23:02 [http-nio-8444-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:24:08 [http-nio-8444-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 06:26:42 [http-nio-8444-exec-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 07:02:44 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 07:21:16 [http-nio-8444-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 10:01:45 [http-nio-8444-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 10:43:03 [http-nio-8444-exec-10] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 10:51:10 [http-nio-8444-exec-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 10:51:52 [http-nio-8444-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 10:53:38 [http-nio-8444-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 11:00:45 [http-nio-8444-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 11:02:28 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 11:03:16 [http-nio-8444-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 14:03:08 [http-nio-8444-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 15:21:46 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 19:57:39 [http-nio-8444-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
2020-11-19 19:59:39 [http-nio-8444-exec-9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "tb_actvity" does not exist
  Position: 25
